### PR TITLE
Added support for 'Meta' keys

### PR DESCRIPTION
**Pull request by JochenHeizmann**
It seems like the library doesn't have support for MetaKeys (Command on Mac OS, Windows Key on Windows Systems).

Would also be great if you can update the dependency in https://github.com/soska/react-keyboardist after you accepted the pull request :-)

### CODE REVIEW

**Comment by beevelop** [comment]
@soska: This feature would be awesome!

**Comment by bastian1993** [comment]
Oh yes, this would be great.

**Comment by nero408** [comment]
Amazing idea! Please accept this pull request

**Comment by abrkir** [comment]
yup, go ahead @soska

**Comment by leonard1311** [comment]
sounds good to me :)

**Comment by soska** [comment]
Thanks! this is a great idea. Merging.

**Comment by beevelop** [comment]
Awesome, thank you 🍻

**Comment by soska** [comment]
I haven't touched this repository or published anything to npm in over a year and I just had some free minutes, but please let me know if I screwed anything. 

And thanks a lot for the PR and the comments, I thought nobody cared about my little project here.

**Comment by beevelop** [comment]
Not an issue, this is the case with a lot of Open Source projects and it is totally fine. We do care about your little project and keep you updated if we need any changes ✌️Thank you from the whole team 🍪

**Pull request merged**
